name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r  requirements.txt
        pip install pytest  --cov=your_package_name pytest-cov codecov

    - name: Run tests with coverage
      run: |
       pytest  --cov-report=xml:coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml